db:
  port: 110
spring:
  mail:
    host: smtp.qq.com # 发送邮件服务器
    protocol: smtp  # 服务协议
    username: 994482866@qq.com # 发送邮件账户
    password: kskmgdondyrgbfjh # 授权码
    test-connection: true
    from: 994482866@qq.com #
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          port: 465 #
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
